# get list of all persons
GET http://localhost:3001/api/persons/

###
#Get info of a single person
GET http://localhost:3001/api/persons/1

###
#Delete a single person
DELETE http://localhost:3001/api/persons/1

###
#Add a new person
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "AB",
  "number": "06 66 69 70 76"
}